install.packages(c("shiny", "httr", "jsonlite", "dplyr", "ggplot2", "corrplot", "leaflet", "htmlwidgets", "DT", "shinymanager","sf"))
library(shiny)
library(httr)
library(jsonlite)
library(dplyr)
library(ggplot2)
library(corrplot)
library(leaflet)
library(htmlwidgets)
library(DT)
library(shinymanager)
library(sf)
library(sp)